- id: '1538408433536'
  alias: Notify hass on
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant just started!
    service: notify.pushbullet_notify
- id: '1538408477552'
  alias: Notify hass off
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant just stopped working!
    service: notify.pushbullet_notify
- id: '1254561251235'
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: A update for Home Assistant is available.
    service: notify.pushbullet_notify
- id: '1538417197012'
  alias: test automation
  trigger:
  - at: '20:07:40'
    platform: time
  condition: []
  action:
  - data:
      message: TEST MESSAGE
      data:
        file_url: http://cdn.thegadgetflow.com/wp-content/uploads/2015/07/WORX-Landroid-Robotic-Lawn-Mower-01.jpg
    service: notify.pushbullet_notify
