homeassistant:
  # This is the legacy auth method. Need to change when NodeRed supports new auth system.
  auth_providers:
  - type: legacy_api_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   api_password: !secret http_password
#   base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

lovelace:
  mode: yaml

recorder:
  exclude:
    domains:
    - automation
    - updater
    - camera
    - device_tracker
    entities:
    - sensor.worldclock_sensor
    - sensor.mot_stan
    - sensor.mot_torslanda
    - sensor.season
    - sun.sun
    - sensor.waze_travel_time
    - sensor.yr_fog
    - sensor.yr_high_clouds
    - sensor.yr_low_clouds
    - sensor.yr_medium_clouds
    - sensor.yr_symbol
    - switch.ip_webcam_exposure_lock
    - switch.ip_webcam_focus
    - switch.ip_webcam_frontfacing_camera
    - switch.ip_webcam_gps_active
    - switch.ip_webcam_night_vision
    - switch.ip_webcam_overlay
    - switch.ip_webcam_torch
    - switch.ip_webcam_video_recording
    - switch.ip_webcam_white_balance_lock
    - persistent_notification.httplogin

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - updater

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone:
  - name: School
    latitude: !secret school_lat
    longitude: !secret school_long
    radius: 150
    icon: mdi:school

# Track the sun
sun:

# Text to speech
tts:
  # - platform: google
  #   cache: true
  #   cache_dir: /tmp/tts
  #   time_memory: 180
  - platform: voicerss
    api_key: !secret voicerss_api   

# Cloud settings
cloud:
  # google_actions:
  #   # filter:
  #   #   exclude_domains:
  #   #     - group
  #   entity_config:
  #         light.theater_lights:
  #           name: Guests
  #           aliases:
  #           - Guest
  #           - visitor
  #           - Visitors

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
####################################################################################
#Checks for updates to custom components and cards
custom_updater:
###################
# media
media_player:
  - platform: webostv
    host: 192.168.1.147
    name: LG Smart TV
  #other settings
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac
  # spotify integration
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
  - platform: plex
  # Make the browser be the media player
  - platform: floorplan_speaker
    name: my_lovelace_player
###################################################################################
# light:
#   - platform: template
#     lights:
#       theater_lights:
#         friendly_name: "Guests"
#         turn_on:
#           # service: script.1536948300132
#         turn_off:
#           # service: script.1536948324762
#################################################################################
input_select:
    house_mode:
        name: House mode
        options:
            - Morning
            - Day
            - Evening
            - Night
    presence:
        name: Presence
        options:
            - Home
            - Away
            - Vacation
#################################################################################
#Booleans
input_boolean:
  adrian_home:
    name: Adrian status
    initial: on
  ella_home:
    name: Ella status
    initial: on
  mamma_home:
    name: Mamma status
    initial: on
  pappa_home:
    name: Pappa status
    initial: on
  guest:
    name: Guest status
    initial: off
  home_occupied:
    name: Home occupied
#################################################################################
device_tracker:
 - platform: nmap_tracker
   hosts: 192.168.1.0-250
   exclude:
     - 192.168.1.148
   interval_seconds: 60
   consider_home: 600
 - platform: bluetooth_tracker
   interval_seconds: 50
asuswrt:
  host: 192.168.1.1
  username: !secret routername
  password: !secret routerpassword
#################################################################################
#Webcam
android_ip_webcam:
  - host: 192.168.1.149
    port: 8080
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
###################################################################################
#cameras
camera:
  - platform: generic
    name: Hjalmar Brantingsplatsen
    still_image_url: http://data.goteborg.se/TrafficCamera/v0.2/CameraImage/83a5905d-7889-4bae-bd6d-0a7e67f4f6af/51?time=2018-09-0319:53:46&maxage=20

  - platform: generic
    name: Mot Hjalmar
    still_image_url: http://data.goteborg.se/TrafficCamera/v0.2/CameraImage/83a5905d-7889-4bae-bd6d-0a7e67f4f6af/99?time=2018-09-0320:00:31&maxage=20

  - platform: generic
    name: Chalmers
    still_image_url: http://data.goteborg.se/TrafficCamera/v0.2/CameraImage/83a5905d-7889-4bae-bd6d-0a7e67f4f6af/17?time=2018-09-0320:05:16&maxage=20

  - platform: generic
    name: Göta älvbron från Hisingen
    still_image_url: http://data.goteborg.se/TrafficCamera/v0.2/CameraImage/83a5905d-7889-4bae-bd6d-0a7e67f4f6af/98?time=2018-09-0320:06:05&maxage=20

  - platform: generic
    name: Nordstan mot Göta älvbron
    still_image_url: http://data.goteborg.se/TrafficCamera/v0.2/CameraImage/83a5905d-7889-4bae-bd6d-0a7e67f4f6af/30?time=2018-09-0320:07:02&maxage=20

###################################################################################
#ifttt
ifttt:
  key: !secret iftt_key
###################################################################################
sensor:
# Weather prediction
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
    #Clock
  - platform: worldclock
    time_zone: Europe/Stockholm
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours
    #Speed test
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload

    #weather information from darksky
  - platform: darksky
    name: Darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - icon
      - dew_point
      - daily_summary
      - temperature
      - uv_index
      - humidity
    update_interval: '00:03:10'

#Outputs the current season. meteorological     
  - platform: season
    type: meteorological

#Västtrafik
  - platform: vasttrafik
    key: !secret vasttrafik_key
    secret: !secret vasttrafik_secret
    departures:
      - name: Mot Stan
        from: Kvisljungeby
        heading: Nordstan
        delay: 8
      - name: Mot Torslanda
        from: Kvisljungeby
        heading: Torslandakrysset
        delay: 8

#haveibeenpwned
  - platform: haveibeenpwned
    email:
      - !secret email_1
      - !secret email_2
      - !secret email_3
      - !secret email_4
      - !secret email_5

#Worx landroid status
  - platform: worxlandroid
    host: 192.168.1.123
    pin: "0000"

#lastfm information. Currently scrobbling what.
#possibility to automate light settings depending
#on what song is being played for example.
  - platform: lastfm
    api_key: !secret lastfm_api
    users:
      - !secret truck

# Waze travel time
  - platform: waze_travel_time
    origin: !secret home_addres
    destination: !secret school_addres
    region: 'EU'

#Trafikverket data
  - platform: trafikverket_weatherstation
    name: Trafikverket Öxnäs
    api_key: !secret trafikverket_api
    station: Öxnäs
    monitored_conditions:
        - air_temp
        - road_temp
        - humidity
        - precipitation
        - wind_direction
        - wind_direction_text
        - wind_speed
################################################################################
weather:
  - platform: darksky
    name: Darksky
    api_key: !secret darksky_key
    mode: daily
  - platform: yweather
    name: Yahoo weather forecast

smhi:
################################################################################
#notifications
notify:
  - name: pushbullet_notify
    platform: pushbullet
    api_key: !secret pushbullet_key
#LG Smart TV
  - platform: webostv
    name: livingroom_tv
    host: 192.168.1.147
#Telegram bot
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_id
#############################################################################
# Node red short cut
panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.1.148:1880/'
##############################################################################
#A telegram bot using polling
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id
##############################################################################
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 10
    delay_time: 10
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
##############################################################################
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml