title: My Awesome Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/gauge-card/gauge-card.js
    type: js
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/alarm_control_panel-card/alarm_control_panel-card.js
    type: js
  - url: /local/lovelace-player.js?3
    type: js
  - url: /local/lovelace-player-config.js?15
    type: js
  - url: /local/popup-card.js?1
    type: js
  - url: https://unpkg.com/moment@2.23.0/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.2.2
    type: module
  - url: /local/custom_ui/weather-card.js
    type: js

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/local/background.png") fixed

# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router
########################################################################################################################################
views:
  - icon: mdi:home-variant
    # View tab title.
    title: Home
    # Optional unique id for direct access /lovelace/${id}
    path: home
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - id: 2bcb114565d14bdfa7046155ca94c83a  # Automatically created id
        type: entity-filter
        entities:
          - input_boolean.adrian_home
          - input_boolean.ella_home
          - input_boolean.pappa_home
          - input_boolean.mamma_home
          - input_boolean.guest

        state_filter:
          - 'on'
        card:
          type: glance
          title: People at home
          show_state: false

        # The picture entity card will represent an entity with a picture
        # nice image https://www.home-assistant.io/images/default-social.png
      - id: 1ce3729d67ed4f9482be95766fcb40a6  # Automatically created id
        type: picture-elements
        image: /local/images/lovelace_day state_base.jpg
        elements:
          - type: image
            entity: input_select.house_mode
            image: /local/images/lovelace_day state_base.jpg
            state_image:
              "Morning": /local/images/lovelace_day_state_morning.png
              "Night": /local/images/lovelace_day_state_night.png
            state_filter:
              "Night": opacity(95%)
            style:
              top: 50%
              left: 50%
              width: 100%
      - id: 1ce3729d67ed4f948gfsja2kfh4b40a6
        type: custom:calendar-card
        title: "Calendar"
        entities: 
        - !secret calendar_1_entity
        - !secret calendar_2_entity
        - !secret calendar_3_entity
        - !secret calendar_4_entity
        - !secret calendar_5_entity
        - !secret calendar_6_entity

########################################################################################################################################
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:weather-cloudy
    path: status
    # Title of the view. Will be used as the tooltip for tab icon
    title: Weather
    
    type: vertical-stack
    cards:
    - id: 112254f5b5a64d16a62bde05cd30b5ff  # Automatically created id
      type: horizontal-stack
      cards:
          - type: gauge
            name: Utomhus temp
            entity: input_number.temperature_home
            unit: °C
            min: -15
            max: 35   
            severity:
              yellow: 0
              green: 10
              red: 25

    - id: sy89sh98sdf8h893h89hs89dfh83244f # Manually created id
      type: entities
      entities: 
      - sensor.season
      - sensor.trafikverket_oxnas_road_temperature

  
    - id: 216824be83754eb7922bf2df57782a96  # Manually created id
      type: horizontal-stack
      cards:
      - type: "custom:weather-card"
        entity_weather: weather.smhi_home
        entity_sun: sun.sun

########################################################################################################################################
  - icon: mdi:music
    path: media
    title: Multi Media
    type: vertical-stack
    cards:
      - id: 42ebabb7d68a41a4b6018ae5bf053701  # Automatically created id
        type: vertical-stack
        cards:
        - type: markdown
          content: "## Övervåningen"
        - type: vertical-stack
          cards:
          - type: entities
            entities:
              - sensor.lastfm_adr29truck
        - type: horizontal-stack
          cards:
          - type: conditional
            conditions:
              - entity: media_player.my_room_speaker
                state_not: "unavailable"
              - entity: media_player.my_room_speaker
                state_not: "off"
            card:
              type: media-control
              entity: media_player.my_room_speaker
          - type: conditional
            conditions:
            - entity:  media_player.home
              state_not: "unavailable"
            - entity: media_player.my_room_speaker
              state_not: "playing"
            card:
              type: media-control
              entity: media_player.home
      - id: aa1f2a8b6f274af2b0101750b6b2391a  # Automatically created id
        type: vertical-stack
        cards:
        - type: markdown
          content: "## Nedervåningen"
        - type: horizontal-stack
          cards:
          - type: conditional
            conditions:
              - entity: media_player.lg_smart_tv
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.lg_smart_tv
          - type: conditional
            conditions:
            - entity:  media_player.chromecast3041
              state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.chromecast3041
          - type: conditional
            conditions:
            - entity: media_player.lg_oled55c7vz
              state_not: "unavailable"
            card:
            - type: media-control
              entity: media_player.lg_oled55c7vz
          - type: conditional
            conditions:
              - entity: media_player.neder_vaningen
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.neder_vaningen
        - type: horizontal-stack
          cards:
          - type: conditional
            conditions:
              - entity: media_player.vardagsrummet
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.vardagsrummet
          - type: conditional
            conditions:
              - entity: media_player.hela_huset
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.hela_huset
      # - id: 8aeb3bf7fd5f4d128829bf031a513c14  # Automatically created id
      #   type: vertical-stack
      #   cards:
      #     - type: horizontal-stack
      #       cards:
      #       - type: conditional
      #         conditions:
      #           - entity: media_player.chromecastaudio0617
      #             state_not: "unavailable"
      #         card:
      #           type: media-control
                # entity: media_player.chromecastaudio0617

########################################################################################################################################
  - icon: mdi:bus
    path: commute
    title: Commute
    type: vertical-stack
    cards:
      - id: d2a77555fd6944ababdf4780ede74c69  # Automatically created id
        type: horizontal-stack
        cards:
          - type: glance
            title: "                               Nästa Buss"
            entities:
              - sensor.buss_mot_stan
              - sensor.buss_mot_torslanda
            columns: 2
            # show_name: false
      - id: 49e6ad58317e44f88e6ee07b873ec08d  # Automatically created id
        type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.hjalmar_brantingsplatsen
            camera_image: camera.hjalmar_brantingsplatsen
            show_state: false

          - type: picture-entity
            entity: camera.mot_hjalmar
            camera_image: camera.mot_hjalmar
            show_state: false
      - id: 4cc67686842b424a9787ca656b42ba9b  # Automatically created id
        type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.gota_alvbron_fran_hisingen
            camera_image: camera.gota_alvbron_fran_hisingen
            show_state: false

          - type: picture-entity
            entity: camera.chalmers
            camera_image: camera.chalmers
            show_state: false
      - id: 5d467f7776b043fc94cf8fc4d655281b  # Automatically created id
        type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.nordstan_mot_gota_alvbron
            camera_image: camera.nordstan_mot_gota_alvbron
            show_state: false
            
      # This creates a popup when pressed but also a big whitespace, rendering the site non centered
      # - id: 5d467f7hslb043fc34nf8fc4d655281b # Manually created id
      #   type: custom:popup-card
      #   entity: camera.nordstan_mot_gota_alvbron
      #   title: Time of day
      #   card:
      #     type: entities
      #     entities:
      #       - input_select.house_mode
########################################################################################################################################
  - icon: mdi:robot-vacuum-variant
    path: assistants
    title: Assistants
    type: vertical-stack
    cards:
      - id: 9245cb5f890f473eab1efa3c359ab799  # Automatically created id
        type: horizontal-stack
        cards:
          - type: glance
            entities:
              - sensor.worxlandroidstate
              - sensor.worxlandroidbattery
            columns: 2
########################################################################################################################################
  - icon: mdi:settings
    path: settings
    title: Settings
    cards:
      - type: vertical-stack
        cards:
        - id: 3b3936fd75254bddaddd8a6f6fe3e615  # Automatically created id
          type: horizontal-stack
          cards:
            - type: custom:tracker-card
              title:
              trackers:
                - sensor.custom_card_tracker
                - sensor.custom_component_tracker
        - type: conditional
          conditions:
          - entity: updater.updater
            state_not: 
            - "unavailable"
            - "off"
            - "unkown"
          card:
            type: entities
            entities: 
            - updater.updater
        - theme: Backend-selected
          title: Settings
          show_header_toggle: false
          id: ef0e127ba990408db4fca9f574f14d6c  # Automatically created id
          type: entities
          entities:
            - input_boolean.guest
            - type: divider
            - group.all_automations
      - type: vertical-stack
        cards: 
        - id: hdjashdjhakjhsd21414asde21ea45  # Manually created id
          type: glance
          entities:
          - input_number.download_speed_used
          - input_number.upload_speed_used

