- alias: 'Krisinformation Alert 1'
  id: 'alert1'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.krisinformation_goREDACTED
    to: "Alert"
  action:
    - service: notify.homeassistant
      data_template:
        message: >
          {{states.sensor.krisinformation_goREDACTED.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_goREDACTED.attributes.messages[0].Message}} {{states.sensor.krisinformation_goREDACTED.attributes.messages[0].Web}}

- alias: 'Krisinformation Alert 2'
  id: 'alert2'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.krisinformation_sverige
    to: "Alert"
  action:
    - service: notify.homeassistant
      data_template:
        message: >
          {{states.sensor.krisinformation_sverige.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_sverige.attributes.messages[0].Message}} {{states.sensor.krisinformation_sverige.attributes.messages[0].Web}}